
import { ShoppingItem } from './types';

export const ALL_GROCERY_ITEMS: ShoppingItem[] = [
    { name: 'Milk', emoji: '🥛' },
    { name: 'Bread', emoji: '🍞' },
    { name: 'Eggs', emoji: '🥚' },
    { name: 'Butter', emoji: '🧈' },
    { name: 'Cheese', emoji: '🧀' },
    { name: 'Apples', emoji: '🍎' },
    { name: 'Bananas', emoji: '🍌' },
    { name: 'Oranges', emoji: '🍊' },
    { name: 'Grapes', emoji: '🍇' },
    { name: 'Strawberries', emoji: '🍓' },
    { name: 'Blueberries', emoji: '🫐' },
    { name: 'Carrots', emoji: '🥕' },
    { name: 'Broccoli', emoji: '🥦' },
    { name: 'Spinach', emoji: '🥬' },
    { name: 'Tomatoes', emoji: '🍅' },
    { name: 'Potatoes', emoji: '🥔' },
    { name: 'Onions', emoji: '🧅' },
    { name: 'Garlic', emoji: '🧄' },
    { name: 'Chicken', emoji: '🍗' },
    { name: 'Beef', emoji: '🥩' },
    { name: 'Fish', emoji: '🐟' },
    { name: 'Rice', emoji: '🍚' },
    { name: 'Pasta', emoji: '🍝' },
    { name: 'Cereal', emoji: '🥣' },
    { name: 'Coffee', emoji: '☕' },
    { name: 'Tea', emoji: '🫖' },
    { name: 'Juice', emoji: '🧃' },
    { name: 'Water', emoji: '💧' },
    { name: 'Yogurt', emoji: '🍦' },
    { name: 'Sugar', emoji: '🧂' },
    { name: 'Flour', emoji: '🥡' },
    { name: 'Olive Oil', emoji: '🫒' },
    { name: 'Soap', emoji: '🧼' },
    { name: 'Shampoo', emoji: '🧴' },
    { name: 'Toilet Paper', emoji: '🧻' },
    { name: 'Paper Towels', emoji: '🧻' },
    { name: 'Cookies', emoji: '🍪' },
    { name: 'Chocolate', emoji: '🍫' },
    { name: 'Ice Cream', emoji: '🍨' },
    { name: 'Pizza', emoji: '🍕' },
    { name: 'Avocado', emoji: '🥑' },
    { name: 'Bell Pepper', emoji: '🫑' },
    { name: 'Cucumber', emoji: '🥒' },
    { name: 'Lettuce', emoji: '🥬' },
    { name: 'Mushrooms', emoji: '🍄' },
    { name: 'Pineapple', emoji: '🍍' },
    { name: 'Watermelon', emoji: '🍉' },
    { name: 'Lemon', emoji: '🍋' },
    { name: 'Lime', emoji: '🍋' },
    { name: 'Honey', emoji: '🍯' },
    { name: 'Jam', emoji: '🍓' },
    { name: 'Peanut Butter', emoji: '🥜' },
    { name: 'Ketchup', emoji: '🍅' },
    { name: 'Mustard', emoji: '🌭' },
    { name: 'Mayonnaise', emoji: '🥚' },
];
